services:
  - type: web
    name: channels-dvr
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8089
    disk:
      name: channels-data
      mountPath: /channels-dvr/data
      sizeGB: 1
