services:
  - type: web
    name: channels-dvr
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8089
      - key: CHANNELS_DVR_PORT
        value: 8089
